# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeastCostPath_dialog_base.ui'
#
# Created: Tue Nov 17 04:07:50 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName(_fromUtf8("Main_Window"))
        Main_Window.setEnabled(True)
        Main_Window.resize(583, 475)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        Main_Window.setFont(font)
        Main_Window.setAutoFillBackground(False)
        Main_Window.setSizeGripEnabled(True)
        Main_Window.setModal(True)
        self.button_box = QtGui.QDialogButtonBox(Main_Window)
        self.button_box.setGeometry(QtCore.QRect(350, 430, 211, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.label = QtGui.QLabel(Main_Window)
        self.label.setGeometry(QtCore.QRect(20, 70, 231, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Main_Window)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 241, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Main_Window)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 241, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Main_Window)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Main_Window)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Main_Window)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 191, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Main_Window)
        self.label_7.setGeometry(QtCore.QRect(20, 310, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Main_Window)
        self.label_8.setGeometry(QtCore.QRect(20, 340, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Input_dem = QtGui.QLineEdit(Main_Window)
        self.Input_dem.setGeometry(QtCore.QRect(230, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Input_dem.setFont(font)
        self.Input_dem.setDragEnabled(True)
        self.Input_dem.setObjectName(_fromUtf8("Input_dem"))
        self.Title = QtGui.QLabel(Main_Window)
        self.Title.setGeometry(QtCore.QRect(160, 10, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName(_fromUtf8("Title"))
        self.label_9 = QtGui.QLabel(Main_Window)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 341, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Main_Window)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 261, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Browse_dem = QtGui.QPushButton(Main_Window)
        self.Browse_dem.setGeometry(QtCore.QRect(510, 70, 51, 23))
        self.Browse_dem.setObjectName(_fromUtf8("Browse_dem"))
        self.line = QtGui.QFrame(Main_Window)
        self.line.setGeometry(QtCore.QRect(20, 270, 541, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.Input_cost = QtGui.QLineEdit(Main_Window)
        self.Input_cost.setGeometry(QtCore.QRect(230, 100, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Input_cost.setFont(font)
        self.Input_cost.setDragEnabled(True)
        self.Input_cost.setObjectName(_fromUtf8("Input_cost"))
        self.Browse_cost = QtGui.QPushButton(Main_Window)
        self.Browse_cost.setGeometry(QtCore.QRect(510, 100, 51, 23))
        self.Browse_cost.setObjectName(_fromUtf8("Browse_cost"))
        self.X_Start = QtGui.QLineEdit(Main_Window)
        self.X_Start.setGeometry(QtCore.QRect(250, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.X_Start.setFont(font)
        self.X_Start.setText(_fromUtf8(""))
        self.X_Start.setDragEnabled(True)
        self.X_Start.setObjectName(_fromUtf8("X_Start"))
        self.Y_Start = QtGui.QLineEdit(Main_Window)
        self.Y_Start.setGeometry(QtCore.QRect(410, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Y_Start.setFont(font)
        self.Y_Start.setDragEnabled(True)
        self.Y_Start.setObjectName(_fromUtf8("Y_Start"))
        self.X = QtGui.QLabel(Main_Window)
        self.X.setGeometry(QtCore.QRect(230, 150, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.X.setFont(font)
        self.X.setObjectName(_fromUtf8("X"))
        self.Y = QtGui.QLabel(Main_Window)
        self.Y.setGeometry(QtCore.QRect(390, 150, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Y.setFont(font)
        self.Y.setObjectName(_fromUtf8("Y"))
        self.X_2 = QtGui.QLabel(Main_Window)
        self.X_2.setGeometry(QtCore.QRect(230, 180, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.X_2.setFont(font)
        self.X_2.setObjectName(_fromUtf8("X_2"))
        self.X_3 = QtGui.QLabel(Main_Window)
        self.X_3.setGeometry(QtCore.QRect(390, 180, 31, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.X_3.setFont(font)
        self.X_3.setObjectName(_fromUtf8("X_3"))
        self.Y_End = QtGui.QLineEdit(Main_Window)
        self.Y_End.setGeometry(QtCore.QRect(410, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Y_End.setFont(font)
        self.Y_End.setDragEnabled(True)
        self.Y_End.setObjectName(_fromUtf8("Y_End"))
        self.X_End = QtGui.QLineEdit(Main_Window)
        self.X_End.setGeometry(QtCore.QRect(250, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.X_End.setFont(font)
        self.X_End.setText(_fromUtf8(""))
        self.X_End.setDragEnabled(True)
        self.X_End.setObjectName(_fromUtf8("X_End"))
        self.Heuristic = QtGui.QComboBox(Main_Window)
        self.Heuristic.setGeometry(QtCore.QRect(230, 210, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Heuristic.setFont(font)
        self.Heuristic.setObjectName(_fromUtf8("Heuristic"))
        self.Heuristic.addItem(_fromUtf8(""))
        self.Heuristic.addItem(_fromUtf8(""))
        self.Heuristic.addItem(_fromUtf8(""))
        self.Browse_slope_w = QtGui.QPushButton(Main_Window)
        self.Browse_slope_w.setGeometry(QtCore.QRect(510, 240, 51, 23))
        self.Browse_slope_w.setObjectName(_fromUtf8("Browse_slope_w"))
        self.Input_slope_w = QtGui.QLineEdit(Main_Window)
        self.Input_slope_w.setGeometry(QtCore.QRect(230, 240, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Input_slope_w.setFont(font)
        self.Input_slope_w.setDragEnabled(True)
        self.Input_slope_w.setObjectName(_fromUtf8("Input_slope_w"))
        self.Output_raster = QtGui.QLineEdit(Main_Window)
        self.Output_raster.setGeometry(QtCore.QRect(230, 310, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Output_raster.setFont(font)
        self.Output_raster.setDragEnabled(True)
        self.Output_raster.setObjectName(_fromUtf8("Output_raster"))
        self.Browse_raster = QtGui.QPushButton(Main_Window)
        self.Browse_raster.setGeometry(QtCore.QRect(510, 310, 51, 23))
        self.Browse_raster.setObjectName(_fromUtf8("Browse_raster"))
        self.Output_vector = QtGui.QLineEdit(Main_Window)
        self.Output_vector.setGeometry(QtCore.QRect(230, 340, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Output_vector.setFont(font)
        self.Output_vector.setDragEnabled(True)
        self.Output_vector.setObjectName(_fromUtf8("Output_vector"))
        self.Browse_vector = QtGui.QPushButton(Main_Window)
        self.Browse_vector.setGeometry(QtCore.QRect(510, 340, 51, 23))
        self.Browse_vector.setObjectName(_fromUtf8("Browse_vector"))
        self.label_11 = QtGui.QLabel(Main_Window)
        self.label_11.setGeometry(QtCore.QRect(20, 130, 471, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.Browse_acc = QtGui.QPushButton(Main_Window)
        self.Browse_acc.setGeometry(QtCore.QRect(510, 370, 51, 23))
        self.Browse_acc.setObjectName(_fromUtf8("Browse_acc"))
        self.Output_acc = QtGui.QLineEdit(Main_Window)
        self.Output_acc.setGeometry(QtCore.QRect(230, 370, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Output_acc.setFont(font)
        self.Output_acc.setDragEnabled(True)
        self.Output_acc.setObjectName(_fromUtf8("Output_acc"))
        self.label_12 = QtGui.QLabel(Main_Window)
        self.label_12.setGeometry(QtCore.QRect(20, 370, 231, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.Title_5 = QtGui.QLabel(Main_Window)
        self.Title_5.setGeometry(QtCore.QRect(20, 440, 201, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Title_5.setFont(font)
        self.Title_5.setObjectName(_fromUtf8("Title_5"))
        self.Title_4 = QtGui.QLabel(Main_Window)
        self.Title_4.setGeometry(QtCore.QRect(20, 430, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Title_4.setFont(font)
        self.Title_4.setObjectName(_fromUtf8("Title_4"))
        self.Title_2 = QtGui.QLabel(Main_Window)
        self.Title_2.setGeometry(QtCore.QRect(20, 410, 301, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Title_2.setFont(font)
        self.Title_2.setObjectName(_fromUtf8("Title_2"))
        self.Title_3 = QtGui.QLabel(Main_Window)
        self.Title_3.setGeometry(QtCore.QRect(20, 420, 231, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Title_3.setFont(font)
        self.Title_3.setObjectName(_fromUtf8("Title_3"))

        self.retranslateUi(Main_Window)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), Main_Window.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), Main_Window.reject)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        Main_Window.setWindowTitle(_translate("Main_Window", "Least Cost Path", None))
        self.label.setText(_translate("Main_Window", "Input DEM Surface ", None))
        self.label_2.setText(_translate("Main_Window", "Input COST Surface ", None))
        self.label_3.setText(_translate("Main_Window", "Input Start Coordinate ", None))
        self.label_4.setText(_translate("Main_Window", "Input End Coordinate ", None))
        self.label_5.setText(_translate("Main_Window", "Heuristic Type  ", None))
        self.label_6.setText(_translate("Main_Window", "Input Weights Slope (CSV) ", None))
        self.label_7.setText(_translate("Main_Window", "Output PATH in Raster  ", None))
        self.label_8.setText(_translate("Main_Window", "Output PATH in Vector  ", None))
        self.Title.setText(_translate("Main_Window", "Least Cost-Path Analysis ", None))
        self.label_9.setText(_translate("Main_Window", "Determine input Data And Parameter :", None))
        self.label_10.setText(_translate("Main_Window", "Determine output PATH :", None))
        self.Browse_dem.setText(_translate("Main_Window", "....", None))
        self.Browse_cost.setText(_translate("Main_Window", "....", None))
        self.X.setText(_translate("Main_Window", "X", None))
        self.Y.setText(_translate("Main_Window", "Y", None))
        self.X_2.setText(_translate("Main_Window", "X", None))
        self.X_3.setText(_translate("Main_Window", "Y", None))
        self.Heuristic.setItemText(0, _translate("Main_Window", "A* Manhattan", None))
        self.Heuristic.setItemText(1, _translate("Main_Window", "A* Diagonal", None))
        self.Heuristic.setItemText(2, _translate("Main_Window", "A* Euclidean", None))
        self.Browse_slope_w.setText(_translate("Main_Window", "....", None))
        self.Browse_raster.setText(_translate("Main_Window", "....", None))
        self.Browse_vector.setText(_translate("Main_Window", "....", None))
        self.label_11.setText(_translate("Main_Window", "* The coordinate reference system must be projected coordinate system ", None))
        self.Browse_acc.setText(_translate("Main_Window", "....", None))
        self.label_12.setText(_translate("Main_Window", "Output Accumulated Cost  in Raster", None))
        self.Title_5.setText(_translate("Main_Window", "Gadjah Mada University", None))
        self.Title_4.setText(_translate("Main_Window", "Faculty Of Engineering", None))
        self.Title_2.setText(_translate("Main_Window", "Achmad Faizal P S (11/319127/TK/38258)", None))
        self.Title_3.setText(_translate("Main_Window", "Geodetic And Geomatic Engineering", None))

